### Get All Products

GET http://localhost:8080/api/v1/books
Accept: application/json

### Create New Product
POST http://localhost:8080/api/v1/books
Content-Type: application/json
Accept: application/json

{
  "title": "Rog tuf",
  "author": "cecep",
  "rating": 10
}
